# Generated by Django 2.2.13 on 2020-06-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('stars', models.IntegerField(default=3)),
                ('desc_1', models.CharField(max_length=255)),
                ('desc_2', models.CharField(max_length=255)),
                ('desc_3', models.CharField(max_length=255)),
                ('img_1', models.ImageField(upload_to='hotels')),
                ('img_2', models.ImageField(upload_to='hotels')),
                ('img_3', models.ImageField(upload_to='hotels')),
                ('about_us', models.CharField(max_length=255)),
                ('years', models.IntegerField(default=2)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('rom_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suit', 'Suit')], max_length=255)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now_add=True)),
                ('guests', models.IntegerField(default=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='front.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=1000)),
                ('image', models.ImageField(upload_to='gallery')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='front.Hotel')),
            ],
        ),
    ]
