# Generated by Django 2.2.13 on 2020-06-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='desc_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='desc_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='hotels'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='hotels'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
