# Generated by Django 2.2.13 on 2020-06-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20200606_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
