# Generated by Django 2.2.13 on 2020-06-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20200606_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='title_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='title_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='title_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
